fix: add ES2022.RegExp for RegExpIndicesArray; fixes ajv-validator/ajv#2603 (#2604)
without ES2022.RegExp, `npm install` will fail due to RegExpIndicesArray
not being present in the ES2018 lib.

Specifically:

```sh
$ npm install

> ajv@8.18.0 prepublish
> npm run build

> ajv@8.18.0 build
> rm -rf dist && tsc && cp -r lib/refs dist && rm dist/refs/json-schema-2019-09/index.ts && rm dist/refs/json-schema-2020-12/index.ts && rm dist/refs/jtd-schema.ts

node_modules/re2/re2.d.ts:11:15 - error TS2304: Cannot find name 'RegExpIndicesArray'.

11     indices?: RegExpIndicesArray;
                 ~~~~~~~~~~~~~~~~~~

Found 1 error in node_modules/re2/re2.d.ts:11
```